apiVersion : apps/v1
kind: Deployment
metadata:
  name: backendprojecttaskapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backendprojecttaskapp
  template:
    metadata:
      labels:
        app: backendprojecttaskapp 
    spec:
      containers:
        - name: backendprojecttaskapp 
          image: abimbolacontainerregistry.azurecr.io/backendprojecttaskapp
          ports:
          - containerPort: 8080